FROM arm64v8/python:3.9-slim-bullseye

WORKDIR /app

COPY requirements.txt ./
RUN apt-get update && apt-get install -y \
    git \
    gcc \
    build-essential \
    python3-dev \
    libbluetooth-dev \
    && rm -rf /var/lib/apt/lists/*
RUN git clone https://github.com/pybluez/pybluez.git && cd pybluez && python setup.py install
RUN pip install -r requirements.txt

COPY . .

CMD [ "python3", "-u", "./main.py" ]