FROM arm64v8/python:3.9-slim-buster

WORKDIR /app

RUN apt-get update && apt-get install -y git
RUN pip install ptvsd==4.1.3
COPY requirements.txt ./
RUN pip install -r requirements.txt

COPY . .

CMD [ "python3", "-u", "./main.py" ]